// Learning techniques based on Barbara Oakley's principles
// ("Learning How to Learn" / "A Mind for Numbers")
export const OAKLEY_TECHNIQUES = [
  'Focused and diffuse mode',
  'Active recall',
  'Spaced repetition',
  'Chunking',
  'Interleaving',
  'Pomodoro technique',
  'Analogies and metaphors',
  'Teach what you learned (Feynman technique)',
] as const;

export type OakleyTechnique = typeof OAKLEY_TECHNIQUES[number];

export interface CourseModule {
  id: string;
  title: string;
  objectives: string[];
  content: string[];
  technique: OakleyTechnique;
  estimatedMinutes: number;
}

export interface Course {
  id: string;
  name: string;
  description: string;
  category: string;
  level: string;
  modules: CourseModule[];
  recommendedTechniques: OakleyTechnique[];
}

export const COURSES: Course[] = [
  {
    id: 'english-ai',
    name: 'English with AI',
    description:
      'Learn English by practicing with AI assistants, consolidating vocabulary and grammar through active recall and spaced repetition.',
    category: 'Languages',
    level: 'All levels',
    modules: [
      {
        id: 'fundamentals-pronunciation',
        title: 'Fundamentals and pronunciation',
        objectives: [
          'Recognize the basic sounds of the English phonetic alphabet (IPA)',
          'Practice minimal pairs (ship/sheep, bit/beat) with correction from an AI assistant',
        ],
        content: [
          'Introduction to the IPA and sounds that do not exist in your native language',
          'Recording your voice and comparing it with AI-generated native pronunciation',
          'A focused practice session followed by a diffuse-mode break to consolidate learning',
        ],
        technique: 'Focused and diffuse mode',
        estimatedMinutes: 45,
      },
      {
        id: 'vocabulary-active-recall',
        title: 'Vocabulary with active recall flashcards',
        objectives: [
          'Build a deck of flashcards with vocabulary generated and contextualized by AI',
          'Apply self-testing (recall before revealing the answer) on every flashcard',
        ],
        content: [
          'Generating example sentences with AI for each new word',
          'Active recall practice: try to answer before seeing the translation',
          'Logging difficult words for future review sessions',
        ],
        technique: 'Active recall',
        estimatedMinutes: 40,
      },
      {
        id: 'conversational-grammar',
        title: 'Conversational grammar with AI',
        objectives: [
          'Practice verb tenses in a conversational context with an AI tutor',
          'Schedule spaced reviews (1, 3, 7 and 16 days) of the hardest rules',
        ],
        content: [
          'Guided dialogues with automatic grammar error correction',
          'Spaced repetition calendar to reinforce grammar rules',
          'Sentence transformation exercises (present -> past -> conditional)',
        ],
        technique: 'Spaced repetition',
        estimatedMinutes: 50,
      },
      {
        id: 'interleaved-listening',
        title: 'Interleaved listening comprehension',
        objectives: [
          'Train your ear with different accents and speech speeds generated by AI',
          'Alternate between exercise types to improve transfer of learning',
        ],
        content: [
          'Transcribing short AI-generated audio clips with different accents',
          'Alternating between dictation, comprehension questions and oral summaries',
          'Short podcasts that interleave vocabulary from previous modules',
        ],
        technique: 'Interleaving',
        estimatedMinutes: 40,
      },
      {
        id: 'oral-production',
        title: 'Oral production and AI feedback',
        objectives: [
          'Hold 25-minute conversations with an AI conversation partner',
          'Receive and apply structured feedback on fluency and accuracy',
        ],
        content: [
          '25-minute focused Pomodoro conversation sessions with 5-minute breaks',
          'AI feedback on pronunciation, grammar and vocabulary used',
          'Repeating the same conversation while improving detected weak points',
        ],
        technique: 'Pomodoro technique',
        estimatedMinutes: 30,
      },
      {
        id: 'final-project-english',
        title: 'Final project: conversation with AI',
        objectives: [
          'Hold a complete conversation in English on a chosen topic',
          'Explain in your own words the grammar rules applied during the conversation',
        ],
        content: [
          'Recording a final 10-minute conversation with AI',
          'Feynman-style explanation of 3 grammar rules used, as if teaching someone else',
          'Self-assessment using a fluency, vocabulary and grammar rubric',
        ],
        technique: 'Teach what you learned (Feynman technique)',
        estimatedMinutes: 60,
      },
    ],
    recommendedTechniques: ['Active recall', 'Spaced repetition', 'Interleaving'],
  },
  {
    id: 'portuguese-ai',
    name: 'Portuguese with AI',
    description:
      'Master Portuguese by practicing with generative AI, reinforcing long-term memory with spaced repetition and interleaved practice.',
    category: 'Languages',
    level: 'All levels',
    modules: [
      {
        id: 'fundamentals-pronunciation-pt',
        title: 'Fundamentals and pronunciation',
        objectives: [
          'Recognize nasal vowels and sounds unique to Portuguese',
          'Practice minimal pairs (avó/avô, pão/pau) with AI correction',
        ],
        content: [
          'Introduction to nasal vowels and Brazilian/European Portuguese intonation',
          'Recording and comparing your pronunciation with AI-generated native audio',
          'A focused session followed by a diffuse-mode break to consolidate new sounds',
        ],
        technique: 'Focused and diffuse mode',
        estimatedMinutes: 45,
      },
      {
        id: 'vocabulary-active-recall-pt',
        title: 'Vocabulary with active recall flashcards',
        objectives: [
          'Build a deck of flashcards with vocabulary contextualized by AI',
          'Apply self-testing (recall before revealing the answer) on every flashcard',
        ],
        content: [
          'Generating example sentences with AI for each new word',
          'Active recall practice before revealing the translation',
          'Logging false cognates between English and Portuguese',
        ],
        technique: 'Active recall',
        estimatedMinutes: 40,
      },
      {
        id: 'conversational-grammar-pt',
        title: 'Conversational grammar with AI',
        objectives: [
          'Practice verb conjugation in a conversational context with an AI tutor',
          'Schedule spaced reviews of the hardest grammar rules',
        ],
        content: [
          'Guided dialogues with automatic grammar error correction',
          'Spaced repetition calendar for the subjunctive and past tenses',
          'Sentence transformation exercises between verb tenses',
        ],
        technique: 'Spaced repetition',
        estimatedMinutes: 50,
      },
      {
        id: 'interleaved-listening-pt',
        title: 'Interleaved listening comprehension',
        objectives: [
          'Train your ear with Brazilian and European accents generated by AI',
          'Alternate between exercise types to improve transfer of learning',
        ],
        content: [
          'Transcribing short AI-generated audio clips with different accents',
          'Alternating between dictation, comprehension questions and oral summaries',
          'Short podcasts that interleave vocabulary from previous modules',
        ],
        technique: 'Interleaving',
        estimatedMinutes: 40,
      },
      {
        id: 'oral-production-pt',
        title: 'Oral production and AI feedback',
        objectives: [
          'Hold 25-minute conversations with an AI conversation partner',
          'Receive and apply structured feedback on fluency and accuracy',
        ],
        content: [
          '25-minute focused Pomodoro conversation sessions with 5-minute breaks',
          'AI feedback on pronunciation, grammar and vocabulary used',
          'Repeating the same conversation while improving detected weak points',
        ],
        technique: 'Pomodoro technique',
        estimatedMinutes: 30,
      },
      {
        id: 'final-project-portuguese',
        title: 'Final project: conversation with AI',
        objectives: [
          'Hold a complete conversation in Portuguese on a chosen topic',
          'Explain in your own words the grammar rules applied during the conversation',
        ],
        content: [
          'Recording a final 10-minute conversation with AI',
          'Feynman-style explanation of 3 grammar rules used, as if teaching someone else',
          'Self-assessment using a fluency, vocabulary and grammar rubric',
        ],
        technique: 'Teach what you learned (Feynman technique)',
        estimatedMinutes: 60,
      },
    ],
    recommendedTechniques: ['Active recall', 'Spaced repetition', 'Interleaving'],
  },
  {
    id: 'typescript-playwright',
    name: 'TypeScript and Playwright Development',
    description:
      'Master TypeScript and test automation with Playwright by chunking complex concepts and alternating focused and diffuse mode.',
    category: 'Programming',
    level: 'Intermediate',
    modules: [
      {
        id: 'typescript-fundamentals',
        title: 'TypeScript fundamentals',
        objectives: [
          'Understand the static type system and its benefits over JavaScript',
          'Break the learning down into small chunks: primitive types, interfaces and typed functions',
        ],
        content: [
          'Primitive types, arrays, tuples and enums',
          'Interfaces vs. type aliases',
          'Chunking the syllabus into 20-30 minute blocks with short exercises per block',
        ],
        technique: 'Chunking',
        estimatedMinutes: 50,
      },
      {
        id: 'advanced-types-generics',
        title: 'Advanced types and generics',
        objectives: [
          'Apply generics to write reusable, type-safe code',
          'Self-test by explaining from memory what each utility type does before checking the docs',
        ],
        content: [
          'Generics in functions, classes and interfaces',
          'Utility types: Partial, Pick, Omit, Record',
          'Active recall quiz: predict the resulting type before compiling',
        ],
        technique: 'Active recall',
        estimatedMinutes: 55,
      },
      {
        id: 'playwright-setup',
        title: 'Playwright setup',
        objectives: [
          'Install and configure a Playwright project with TypeScript',
          'Understand the folder structure and configuration file',
        ],
        content: [
          'Installation, `playwright.config.ts` and supported browsers',
          'Project structure: tests, fixtures and reports',
          'A focused setup session followed by a diffuse break before writing the first test',
        ],
        technique: 'Focused and diffuse mode',
        estimatedMinutes: 40,
      },
      {
        id: 'e2e-automation',
        title: 'E2E test automation',
        objectives: [
          'Write end-to-end tests combining UI interactions and API calls',
          'Alternate between different assertion and locator types to generalize learning',
        ],
        content: [
          'Locators (`getByRole`, `getByTestId`) and user actions',
          'Visual, text and network assertions interleaved in the same suite',
          'Mixing UI and API tests in the same workflow',
        ],
        technique: 'Interleaving',
        estimatedMinutes: 60,
      },
      {
        id: 'page-object-patterns',
        title: 'Page Object patterns',
        objectives: [
          'Apply the Page Object Model (POM) pattern to keep tests scalable',
          'Reinforce the pattern with spaced reviews across different practice projects',
        ],
        content: [
          'Designing Page Object classes and separating responsibilities',
          'Refactoring existing tests toward POM',
          'Spaced review: rewrite the same POM without looking at the original after a few days',
        ],
        technique: 'Spaced repetition',
        estimatedMinutes: 50,
      },
      {
        id: 'ci-reporting',
        title: 'Continuous integration and reporting',
        objectives: [
          'Integrate the Playwright suite into a CI/CD pipeline',
          'Explain the configured pipeline to a teammate as if they had never seen it',
        ],
        content: [
          'Configuring a GitHub Actions workflow to run tests',
          'Generating and interpreting HTML and trace reports',
          'Feynman-style explanation of the full pipeline, from commit to report',
        ],
        technique: 'Teach what you learned (Feynman technique)',
        estimatedMinutes: 45,
      },
    ],
    recommendedTechniques: ['Chunking', 'Interleaving', 'Focused and diffuse mode'],
  },
  {
    id: 'ai-engineering',
    name: 'AI Engineering',
    description:
      'Build and integrate AI solutions by applying analogies for complex concepts and teaching what you learned to consolidate knowledge.',
    category: 'Artificial Intelligence',
    level: 'Advanced',
    modules: [
      {
        id: 'ai-llm-fundamentals',
        title: 'AI and LLM fundamentals',
        objectives: [
          'Explain with analogies how a language model works at a high level',
          'Distinguish between training, fine-tuning and inference',
        ],
        content: [
          'The "giant autocomplete" analogy to explain LLMs',
          'Tokens, embeddings and context windows explained with everyday metaphors',
          'Differences between base, instruct and reasoning models',
        ],
        technique: 'Analogies and metaphors',
        estimatedMinutes: 50,
      },
      {
        id: 'prompt-engineering',
        title: 'Prompt engineering',
        objectives: [
          'Design effective prompts using role, context and few-shot examples',
          'Actively recall prompting techniques before checking a cheat sheet',
        ],
        content: [
          'Zero-shot, few-shot and chain-of-thought prompting',
          'Prompt templates for classification, summarization and generation tasks',
          'Self-assessment: reconstruct a prompt template from memory before reviewing it',
        ],
        technique: 'Active recall',
        estimatedMinutes: 45,
      },
      {
        id: 'ai-api-integration',
        title: 'AI API integration',
        objectives: [
          'Consume AI model APIs from a TypeScript/Node application',
          'Chunk the integration into blocks: authentication, calling, error handling and streaming',
        ],
        content: [
          'Authentication and secure API key handling',
          'Synchronous calls and response streaming',
          'Error handling, retries and rate limiting',
        ],
        technique: 'Chunking',
        estimatedMinutes: 55,
      },
      {
        id: 'rag-vector-stores',
        title: 'RAG and vector stores',
        objectives: [
          'Implement a basic Retrieval-Augmented Generation (RAG) flow',
          'Alternate between different data types (text, PDF, code) to generalize the RAG pattern',
        ],
        content: [
          'Embeddings and vector databases',
          'Chunking documents and retrieval strategies',
          'Interleaved practice indexing different types of knowledge sources',
        ],
        technique: 'Interleaving',
        estimatedMinutes: 60,
      },
      {
        id: 'ai-agents',
        title: 'AI agents',
        objectives: [
          'Design an AI agent with tools and memory',
          'Alternate focused design sessions with diffuse-mode breaks to resolve architecture blockers',
        ],
        content: [
          'Agent architecture: planning, tools and memory',
          'Orchestrating multi-step flows and tool calls',
          'A focused design session followed by a walk or break in diffuse mode',
        ],
        technique: 'Focused and diffuse mode',
        estimatedMinutes: 55,
      },
      {
        id: 'evaluation-responsible-deployment',
        title: 'Evaluation and responsible deployment',
        objectives: [
          'Define evaluation metrics for AI solutions (accuracy, latency, cost, safety)',
          'Explain the full lifecycle of an AI solution as if teaching a new team',
        ],
        content: [
          'Evaluation metrics and test datasets',
          'Safety, bias and responsibility considerations',
          'Feynman-style explanation of the full cycle: data, model, evaluation and deployment',
        ],
        technique: 'Teach what you learned (Feynman technique)',
        estimatedMinutes: 50,
      },
    ],
    recommendedTechniques: ['Analogies and metaphors', 'Teach what you learned (Feynman technique)', 'Focused and diffuse mode'],
  },
];
